/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ProdutoKvm;
import bean.VendaProdutoKvm;
import dao.Cliente_DAO;
import dao.Produto_DAO;
import java.util.ArrayList;
import java.util.List;
import tools.Util;
import view.JDlgVenda;
import controle.VendaProdutoControle;

/**
 *
 * @author Sebas
 */
public class JDlgVendaProduto extends javax.swing.JDialog {

    JDlgVenda jDlgVenda;
    public VendaProdutoControle vendaProdutoControle;
    Produto_DAO produto_DAO;

    /**
     * Creates new form JDlgInclusaoVendas
     */
    public JDlgVendaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        vendaProdutoControle = new VendaProdutoControle();
        produto_DAO = new Produto_DAO();

        Util.habilitar(false, jTxtTotalKvm);

        Produto_DAO produto_DAO = new Produto_DAO();
        List lista = new ArrayList();
        List listaProdutos = produto_DAO.listAll();
        for (int i = 0; i < listaProdutos.size(); i++) {
            jCboProdutoKvm.addItem((ProdutoKvm) listaProdutos.get(i));
        }

    }

    public VendaProdutoKvm viewBean() {
        VendaProdutoKvm vendaProdutoKvm = new VendaProdutoKvm();
        int quantidadeKvm = Util.strInt(jTxtQuantidadeKvm.getText());
        double totalKvm = Util.strDouble(jTxtTotalKvm.getText());
        vendaProdutoKvm.setProdutoKvm((ProdutoKvm) jCboProdutoKvm.getSelectedItem());

        return vendaProdutoKvm;
    }

    public void beanView(VendaProdutoKvm vendaProdutoKvm) {
        String intStr = Util.intStr(vendaProdutoKvm.getQuantidadeKvm());
        String totalKvm = Util.doubleStr(vendaProdutoKvm.getValorUnitKvm());
        jCboProdutoKvm.setSelectedItem(vendaProdutoKvm.getProdutoKvm());

    }

    public void setTelaAnterior(JDlgVenda jDlgVenda) {
        this.jDlgVenda = jDlgVenda;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboProdutoKvm = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtQuantidadeKvm = new javax.swing.JTextField();
        jTxtValorUnitarioKvm = new javax.swing.JTextField();
        jTxtTotalKvm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produto");

        jCboProdutoKvm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutoKvmItemStateChanged(evt);
            }
        });
        jCboProdutoKvm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboProdutoKvmActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitario");

        jLabel4.setText("Total");

        jTxtQuantidadeKvm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeKvmActionPerformed(evt);
            }
        });
        jTxtQuantidadeKvm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeKvmKeyReleased(evt);
            }
        });

        jTxtValorUnitarioKvm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtValorUnitarioKvmActionPerformed(evt);
            }
        });

        jTxtTotalKvm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalKvmActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboProdutoKvm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtQuantidadeKvm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtValorUnitarioKvm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTotalKvm)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboProdutoKvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtQuantidadeKvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtValorUnitarioKvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTotalKvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboProdutoKvmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboProdutoKvmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboProdutoKvmActionPerformed

    private void jCboProdutoKvmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutoKvmItemStateChanged
        if (jCboProdutoKvm.getSelectedIndex() != -1) { //-1 indica que nenhum item foi selecionado.            
            jTxtQuantidadeKvm.setText("1");
            ProdutoKvm produtoMsl = (ProdutoKvm) jCboProdutoKvm.getSelectedItem();
            jTxtValorUnitarioKvm.setText(Util.doubleStr(produtoMsl.getPrecoKvm()));

        }
    }//GEN-LAST:event_jCboProdutoKvmItemStateChanged

    private void jTxtValorUnitarioKvmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtValorUnitarioKvmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtValorUnitarioKvmActionPerformed

    private void jTxtQuantidadeKvmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKvmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeKvmActionPerformed

    private void jTxtQuantidadeKvmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKvmKeyReleased
    if (jTxtQuantidadeKvm.getText().isEmpty() == false) { // Verifica se o não está vazio
    double unitario = Util.strDouble(jTxtValorUnitarioKvm.getText()); // Converte de texto para um double
    int quantidade = Util.strInt(jTxtQuantidadeKvm.getText()); // Converte de texto para um inteiro
    jTxtTotalKvm.setText(String.valueOf(quantidade * unitario)); 
} else {
    jTxtTotalKvm.setText("0"); // Se o campo de quantidade estiver vazio, define o total como "0"
}

    }//GEN-LAST:event_jTxtQuantidadeKvmKeyReleased

    private void jTxtTotalKvmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalKvmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalKvmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Util.mensagem("Operacao cancelada");
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        VendaProdutoKvm vendaProdutoKvm = new VendaProdutoKvm();// Criação de um novo objeto VendaProdutoKvm para representar um produto vendido
        VendaProdutoControle vendas = new VendaProdutoControle();// Criação de um controle de vendas de produtos
        vendaProdutoKvm.setProdutoKvm((ProdutoKvm) jCboProdutoKvm.getSelectedItem());// Define o produto selecionado no ComboBox na instância de VendaProdutoKvm
        vendaProdutoKvm.setQuantidadeKvm(Util.strInt(jTxtQuantidadeKvm.getText()));// Converte o valor da quantidade (String) do campo de texto para inteiro e define a quantidade do produto vendido
        vendaProdutoKvm.setValorUnitKvm((int) Util.strDouble(jTxtValorUnitarioKvm.getText()));// Converte o valor unitário do produto (String) para double e o define como valor unitário na instância de VendaProdutoKvm
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {// Verifica se o título da janela (getTitle()) começa com a letra "I" (indicando que está inserindo um novo item)
            jDlgVenda.vendaProdutoControle.addBean(vendaProdutoKvm);    // Adiciona o novo produto à lista de produtos controlada pelo diálogo de vendas
        } else {// Atualiza o produto selecionado na lista com os novos valores
            jDlgVenda.vendaProdutoControle.updateBean(jDlgVenda.getSelectedRowProd(), vendaProdutoKvm);
        }


        Util.limparCampos(jTxtQuantidadeKvm);// Limpa o campo de quantidade após a inserção ou atualização do produto


        setVisible(false);// Fecha a janela de diálogo, tornando-a invisível

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendaProduto dialog = new JDlgVendaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<ProdutoMsl> jCboProdutoKvm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtQuantidadeKvm;
    private javax.swing.JTextField jTxtTotalKvm;
    private javax.swing.JTextField jTxtValorUnitarioKvm;
    // End of variables declaration//GEN-END:variables
}
