package bean;
// Generated 28/08/2024 10:07:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteKvm generated by hbm2java
 */
@Entity
@Table(name="cliente_kvm"
    ,catalog="db_kelvin_morel"
)
public class ClienteKvm  implements java.io.Serializable {


     private int idclienteKvm;
     private String nomeKvm;
     private String sobrenomeKvm;
     private String sexoKvm;
     private String cpfKvm;
     private Date dataNascimentoKvm;
     private String telefoneKvm;
     private String celularKvm;
     private String cepKvm;
     private String cidadeKvm;
     private String estadoKvm;
     private String enderecoKvm;
     private String estadoCivilKvm;
     private String idadeKvm;
     private String emailKvm;
     

    public ClienteKvm() {
    }

	
    public ClienteKvm(int idclienteKvm, String nomeKvm, String sobrenomeKvm, String sexoKvm, String cpfKvm, Date dataNascimentoKvm, String telefoneKvm, String celularKvm, String cepKvm, String cidadeKvm, String estadoKvm, String enderecoKvm, String estadoCivilKvm, String idadeKvm, String emailKvm) {
        this.idclienteKvm = idclienteKvm;
        this.nomeKvm = nomeKvm;
        this.sobrenomeKvm = sobrenomeKvm;
        this.sexoKvm = sexoKvm;
        this.cpfKvm = cpfKvm;
        this.dataNascimentoKvm = dataNascimentoKvm;
        this.telefoneKvm = telefoneKvm;
        this.celularKvm = celularKvm;
        this.cepKvm = cepKvm;
        this.cidadeKvm = cidadeKvm;
        this.estadoKvm = estadoKvm;
        this.enderecoKvm = enderecoKvm;
        this.estadoCivilKvm = estadoCivilKvm;
        this.idadeKvm = idadeKvm;
        this.emailKvm = emailKvm;
    }
   
     @Id 

    
    @Column(name="idcliente_kvm", unique=true, nullable=false)
    public int getIdclienteKvm() {
        return this.idclienteKvm;
    }
    
    public void setIdclienteKvm(int idclienteKvm) {
        this.idclienteKvm = idclienteKvm;
    }

    
    @Column(name="nome_kvm", nullable=false, length=20)
    public String getNomeKvm() {
        return this.nomeKvm;
    }
    
    public void setNomeKvm(String nomeKvm) {
        this.nomeKvm = nomeKvm;
    }

    
    @Column(name="sobrenome_kvm", nullable=false, length=20)
    public String getSobrenomeKvm() {
        return this.sobrenomeKvm;
    }
    
    public void setSobrenomeKvm(String sobrenomeKvm) {
        this.sobrenomeKvm = sobrenomeKvm;
    }

    
    @Column(name="sexo_kvm", nullable=false, length=1)
    public String getSexoKvm() {
        return this.sexoKvm;
    }
    
    public void setSexoKvm(String sexoKvm) {
        this.sexoKvm = sexoKvm;
    }

    
    @Column(name="cpf_kvm", nullable=false, length=14)
    public String getCpfKvm() {
        return this.cpfKvm;
    }
    
    public void setCpfKvm(String cpfKvm) {
        this.cpfKvm = cpfKvm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_kvm", nullable=false, length=10)
    public Date getDataNascimentoKvm() {
        return this.dataNascimentoKvm;
    }
    
    public void setDataNascimentoKvm(Date dataNascimentoKvm) {
        this.dataNascimentoKvm = dataNascimentoKvm;
    }

    
    @Column(name="telefone_kvm", nullable=false, length=13)
    public String getTelefoneKvm() {
        return this.telefoneKvm;
    }
    
    public void setTelefoneKvm(String telefoneKvm) {
        this.telefoneKvm = telefoneKvm;
    }

    
    @Column(name="celular_kvm", nullable=false, length=13)
    public String getCelularKvm() {
        return this.celularKvm;
    }
    
    public void setCelularKvm(String celularKvm) {
        this.celularKvm = celularKvm;
    }

    
    @Column(name="cep_kvm", nullable=false, length=7)
    public String getCepKvm() {
        return this.cepKvm;
    }
    
    public void setCepKvm(String cepKvm) {
        this.cepKvm = cepKvm;
    }

    
    @Column(name="cidade_kvm", nullable=false, length=30)
    public String getCidadeKvm() {
        return this.cidadeKvm;
    }
    
    public void setCidadeKvm(String cidadeKvm) {
        this.cidadeKvm = cidadeKvm;
    }

    
    @Column(name="estado_kvm", nullable=false, length=2)
    public String getEstadoKvm() {
        return this.estadoKvm;
    }
    
    public void setEstadoKvm(String estadoKvm) {
        this.estadoKvm = estadoKvm;
    }

    
    @Column(name="endereco_kvm", nullable=false, length=6)
    public String getEnderecoKvm() {
        return this.enderecoKvm;
    }
    
    public void setEnderecoKvm(String enderecoKvm) {
        this.enderecoKvm = enderecoKvm;
    }

    
    @Column(name="estadoCivil_kvm", nullable=false, length=12)
    public String getEstadoCivilKvm() {
        return this.estadoCivilKvm;
    }
    
    public void setEstadoCivilKvm(String estadoCivilKvm) {
        this.estadoCivilKvm = estadoCivilKvm;
    }

    
    @Column(name="idade_kvm", nullable=false, length=3)
    public String getIdadeKvm() {
        return this.idadeKvm;
    }
    
    public void setIdadeKvm(String idadeKvm) {
        this.idadeKvm = idadeKvm;
    }

    
    @Column(name="email_kvm", nullable=false, length=50)
    public String getEmailKvm() {
        return this.emailKvm;
    }
    
    public void setEmailKvm(String emailKvm) {
        this.emailKvm = emailKvm;
    }




}


