package bean;
// Generated 28/08/2024 10:07:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuncionarioKvm generated by hbm2java
 */
@Entity
@Table(name="funcionario_kvm"
    ,catalog="db_kelvin_morel"
)
public class FuncionarioKvm  implements java.io.Serializable {


     private int idfuncionarioKvm;
     private String nomeKvm;
     private String cpfKvm;
     private String emailKvm;
     private String telefoneKvm;
     private String enderecoKvm;
     private String sobrenomeKvm;
     

    public FuncionarioKvm() {
    }

	
    public FuncionarioKvm(int idfuncionarioKvm, String nomeKvm, String cpfKvm, String emailKvm, String telefoneKvm, String enderecoKvm, String sobrenomeKvm) {
        this.idfuncionarioKvm = idfuncionarioKvm;
        this.nomeKvm = nomeKvm;
        this.cpfKvm = cpfKvm;
        this.emailKvm = emailKvm;
        this.telefoneKvm = telefoneKvm;
        this.enderecoKvm = enderecoKvm;
        this.sobrenomeKvm = sobrenomeKvm;
    }

   
     @Id 

    
    @Column(name="idfuncionario_kvm", unique=true, nullable=false)
    public int getIdfuncionarioKvm() {
        return this.idfuncionarioKvm;
    }
    
    public void setIdfuncionarioKvm(int idfuncionarioKvm) {
        this.idfuncionarioKvm = idfuncionarioKvm;
    }

    
    @Column(name="nome_kvm", nullable=false, length=20)
    public String getNomeKvm() {
        return this.nomeKvm;
    }
    
    public void setNomeKvm(String nomeKvm) {
        this.nomeKvm = nomeKvm;
    }

    
    @Column(name="cpf_kvm", nullable=false, length=14)
    public String getCpfKvm() {
        return this.cpfKvm;
    }
    
    public void setCpfKvm(String cpfKvm) {
        this.cpfKvm = cpfKvm;
    }

    
    @Column(name="email_kvm", nullable=false, length=50)
    public String getEmailKvm() {
        return this.emailKvm;
    }
    
    public void setEmailKvm(String emailKvm) {
        this.emailKvm = emailKvm;
    }

    
    @Column(name="telefone_kvm", nullable=false, length=13)
    public String getTelefoneKvm() {
        return this.telefoneKvm;
    }
    
    public void setTelefoneKvm(String telefoneKvm) {
        this.telefoneKvm = telefoneKvm;
    }

    
    @Column(name="endereco_kvm", nullable=false, length=30)
    public String getEnderecoKvm() {
        return this.enderecoKvm;
    }
    
    public void setEnderecoKvm(String enderecoKvm) {
        this.enderecoKvm = enderecoKvm;
    }

    
    @Column(name="sobrenome_kvm", nullable=false, length=20)
    public String getSobrenomeKvm() {
        return this.sobrenomeKvm;
    }
    
    public void setSobrenomeKvm(String sobrenomeKvm) {
        this.sobrenomeKvm = sobrenomeKvm;
    }



}


