package bean;
// Generated 28/08/2024 10:07:57 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoKvm generated by hbm2java
 */
@Entity
@Table(name="produto_kvm"
    ,catalog="db_kelvin_morel"
)
public class ProdutoKvm  implements java.io.Serializable {


     private int idprodutoKvm;
     private String marcaKvm;
     private String modeloKvm;
     private String corKvm;
     private String tamanhoKvm;
     private Double precoKvm;
     private int quantidadeKvm;

    public ProdutoKvm() {
    }

	
    public ProdutoKvm(int idprodutoKvm, String marcaKvm, String modeloKvm, String corKvm, String tamanhoKvm, Double precoKvm, int quantidadeKvm) {
        this.idprodutoKvm = idprodutoKvm;
        this.marcaKvm = marcaKvm;
        this.modeloKvm = modeloKvm;
        this.corKvm = corKvm;
        this.tamanhoKvm = tamanhoKvm;
        this.precoKvm = precoKvm;
        this.quantidadeKvm = quantidadeKvm;
    }

     @Id 

    
    @Column(name="idproduto_kvm", unique=true, nullable=false)
    public int getIdprodutoKvm() {
        return this.idprodutoKvm;
    }
    
    public void setIdprodutoKvm(int idprodutoKvm) {
        this.idprodutoKvm = idprodutoKvm;
    }

    
    @Column(name="marca_kvm", nullable=false, length=45)
    public String getMarcaKvm() {
        return this.marcaKvm;
    }
    
    public void setMarcaKvm(String marcaKvm) {
        this.marcaKvm = marcaKvm;
    }

    
    @Column(name="modelo_kvm", nullable=false, length=45)
    public String getModeloKvm() {
        return this.modeloKvm;
    }
    
    public void setModeloKvm(String modeloKvm) {
        this.modeloKvm = modeloKvm;
    }

    
    @Column(name="cor_kvm", nullable=false, length=30)
    public String getCorKvm() {
        return this.corKvm;
    }
    
    public void setCorKvm(String corKvm) {
        this.corKvm = corKvm;
    }

    
    @Column(name="tamanho_kvm", nullable=false, length=2)
    public String getTamanhoKvm() {
        return this.tamanhoKvm;
    }
    
    public void setTamanhoKvm(String tamanhoKvm) {
        this.tamanhoKvm = tamanhoKvm;
    }

    
    @Column(name="preco_kvm", nullable=false, precision=10)
    public Double getPrecoKvm() {
        return this.precoKvm;
    }
    
    public void setPrecoKvm(Double precoKvm) {
        this.precoKvm = precoKvm;
    }

    
    @Column(name="quantidade_kvm", nullable=false)
    public int getQuantidadeKvm() {
        return this.quantidadeKvm;
    }
    
    public void setQuantidadeKvm(int quantidadeKvm) {
        this.quantidadeKvm = quantidadeKvm;
    }




}


