package bean;
// Generated 28/08/2024 10:07:57 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaProdutoKvm generated by hbm2java
 */
@Entity
@Table(name="vendaProduto_kvm"
    ,catalog="db_kelvin_morel"
)
public class VendaProdutoKvm  implements java.io.Serializable {


     private int idvendaProdutoKvm;
     private ProdutoKvm produtoKvm;
     private VendaKvm vendaKvm;
     private int quantidadeKvm;
     private double valorUnitKvm;

    public VendaProdutoKvm() {
    }

    public VendaProdutoKvm(int idvendaProdutoKvm, ProdutoKvm produtoKvm, VendaKvm vendaKvm, int quantidadeKvm, double valorUnitKvm) {
       this.idvendaProdutoKvm = idvendaProdutoKvm;
       this.produtoKvm = produtoKvm;
       this.vendaKvm = vendaKvm;
       this.quantidadeKvm = quantidadeKvm;
       this.valorUnitKvm = valorUnitKvm;
    }
   
     @Id 

    
    @Column(name="idvendaProduto_kvm", unique=true, nullable=false)
    public int getIdvendaProdutoKvm() {
        return this.idvendaProdutoKvm;
    }
    
    public void setIdvendaProdutoKvm(int idvendaProdutoKvm) {
        this.idvendaProdutoKvm = idvendaProdutoKvm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkproduto_kvm", nullable=false)
    public ProdutoKvm getProdutoKvm() {
        return this.produtoKvm;
    }
    
    public void setProdutoKvm(ProdutoKvm produtoKvm) {
        this.produtoKvm = produtoKvm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkvenda_kvm", nullable=false)
    public VendaKvm getVendaKvm() {
        return this.vendaKvm;
    }
    
    public void setVendaKvm(VendaKvm vendaKvm) {
        this.vendaKvm = vendaKvm;
    }

    
    @Column(name="quantidade_kvm", nullable=false)
    public int getQuantidadeKvm() {
        return this.quantidadeKvm;
    }
    
    public void setQuantidadeKvm(int quantidadeKvm) {
        this.quantidadeKvm = quantidadeKvm;
    }

    
    @Column(name="valorUnit_kvm", nullable=false, precision=10)
    public double getValorUnitKvm() {
        return this.valorUnitKvm;
    }
    
    public void setValorUnitKvm(double valorUnitKvm) {
        this.valorUnitKvm = valorUnitKvm;
    }




}


